[run]
build-tags = ["tools"]

[linters]
enable-all = true
# Linters proven to be valuable, worth keeping even if enable-all is switched off
# enable = [
#   "gosec",
#   "varnamelenff"
# ]
disable = [
  "depguard",
  "exhaustruct",
  "execinquery", # deprecated
  "gomnd",       # deprecated
]

[issues]
exclude-use-default = false
