apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: null # Added by GitHub Actions
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      serviceAccountName: ocomms@ocomms.iam.gserviceaccount.com
      containers:
        - image: null # Added by GitHub Actions
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: ocomms
            - name: TWILIO_API_KEY_SID
              value: SK5249dbf7bdd9d365ae81ba851195ab1f
            - name: TWILIO_API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: twilio-api-key
