apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: null # Added by GitHub Actions
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      serviceAccountName: ocomms@ocomms.iam.gserviceaccount.com
      containers:
        - image: null # Added by GitHub Actions
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: ocomms
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: sendgrid-api-key
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: "1"
                  name: twilio-auth-token
