server:
  port: "8080"
  timeouts:
    ReadHeaderTimeout: 1s
    ReadTimeout: 15s
    WriteTimeout: 15s
    IdleTimeout: 90s

logging:
  format: json
  level: info

i18n:
  defaultLang: en

mail:
  from:
    address: ocomms@infotechottawa.ca
    name: O-Comms
  to:
    address: caleb@infotechottawa.ca
    name: Caleb St-Denis
  sendgrid:
    apiKey: ${SENDGRID_API_KEY}

twilio:
  agentDIDs:
    - "+16138160938"
  auth:
    accountSID: AC9dd9e2eaf471a273968b3f1a18b637cc
    apiKeySID: ${TWILIO_API_KEY_SID}
    apiKeySecret: ${TWILIO_API_KEY_SECRET}
    authToken: ${TWILIO_AUTH_TOKEN}
  recordInboundCalls: true
  recordOutboundCalls: true
  timeouts:
    dialAgents: 10
    gatherAcceptCall: 5
    gatherLanguage: 10
    gatherOutboundNumber: 10
    gatherStartVoicemail: 10
  languages:
    en: en-US
    fr: fr-CA
