server:
  port: "8080"
  timeouts:
    ReadHeaderTimeout: 1s
    ReadTimeout: 15s
    WriteTimeout: 15s
    IdleTimeout: 90s

logging:
  format: json
  level: info

i18n:
  defaultLang: en

twilio:
  agentDIDs:
    - "6138160938"
  auth:
    keySID: ${TWILIO_API_KEY_SID}
    keySecret: ${TWILIO_API_KEY_SECRET}
  recordInboundCalls: true
  recordOutboundCalls: true
  timeouts:
    dialAgents: 10
    gatherAcceptCall: 5
    gatherLanguage: 10
    gatherOutboundNumber: 10
    gatherStartVoicemail: 10
  languages:
    en: en-US
    fr: fr-CA
