# yaml-language-server: $schema=./schema.json
server:
  port: "8080"
  timeouts:
    ReadHeaderTimeout: 1s
    ReadTimeout: 15s
    WriteTimeout: 15s
    IdleTimeout: 90s

logging:
  format: json
  level: info

i18n:
  defaultLang: en

twilio:
  agentDIDs:
    - "6138160938"
  recordInboundCalls: true
  recordOutboundCalls: true
  timeouts:
    dialAgents: 10
    gatherAcceptCall: 5
    gatherLanguage: 10
    gatherOutboundNumber: 10
  voice:
    en: Polly.Stephen-Neural
    fr: Polly.Liam-Neural
