name: Branch cleanup

on: delete

jobs:
  delete-service:
    name: Delete Service
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/setup-gcloud
      - name: Delete service
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          gcloud run services delete ocomms-$BRANCH_NAME
