name: Branch cleanup

on: delete

jobs:
  delete-service:
    name: Delete Service
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-gcloud
      - name: Delete service
        run: |
          gcloud run services delete ocomms-${{ github.event.ref }} --region northamerica-northeast1 --quiet
